<a href="https://colab.research.google.com/github/saroj-shah/NLP_Gen_AI/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
import tensorflow as tf;

In [4]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [5]:
a = torch.empty(2,3)

In [6]:
a

tensor([[1.5766e-19, 1.0256e-08, 2.5637e-09],
        [3.1644e+12, 1.0839e-08, 1.0549e-08]])

In [7]:
type(a)

torch.Tensor

In [11]:
b = torch.empty(1)
b

tensor([0.])

In [12]:
type(b)

torch.Tensor

In [14]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
torch.rand(2,4)

tensor([[0.4282, 0.3679, 0.0017, 0.1899],
        [0.5789, 0.7259, 0.7240, 0.2253]])

In [20]:
torch.rand(2,4)

tensor([[0.7963, 0.1595, 0.9056, 0.2083],
        [0.0435, 0.7368, 0.6329, 0.7251]])

In [22]:
torch.manual_seed(10)
torch.rand(2,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693]])

In [23]:
torch.rand(2,4)

tensor([[0.6178, 0.3304, 0.5479, 0.4440],
        [0.7041, 0.5573, 0.6959, 0.9849]])

In [24]:
torch.manual_seed(10)
torch.rand(2,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693]])

In [25]:
torch.manual_seed(11)
torch.rand(2,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284]])

In [26]:
torch.manual_seed(11)
torch.rand(2,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284]])

In [28]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [31]:
torch.arange(3,9)

tensor([3, 4, 5, 6, 7, 8])

In [30]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
torch.arange(1,9,3)

tensor([1, 4, 7])

In [34]:
torch.linspace(0,10,20)

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [35]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [36]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [37]:
x = torch.tensor([[1,2,3],[3,4,5]])

In [38]:
x.shape

torch.Size([2, 3])

In [39]:
torch.empty_like(x)

tensor([[261555856, 261807696,        80],
        [       64, 265468966,        81]])

In [40]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [42]:
torch.rand_like(x, dtype=torch.float)

tensor([[0.5721, 0.9248, 0.2693],
        [0.7825, 0.2719, 0.4632]])

In [43]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [44]:
x*3

tensor([[ 3,  6,  9],
        [ 9, 12, 15]])

In [45]:
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.0000, 1.3333, 1.6667]])

In [47]:
torch.abs(x)

tensor([[1, 2, 3],
        [3, 4, 5]])

In [48]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [49]:
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [50]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [51]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [53]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [55]:
torch.randint(size=(4,5), low=0,high=10)

tensor([[4, 5, 8, 5, 8],
        [1, 8, 2, 8, 9],
        [2, 3, 1, 7, 0],
        [1, 5, 6, 0, 5]])

In [60]:
e= torch.randint(size=(4,5), low=-10,high=10)

In [61]:
e

tensor([[  1,   5,  -7,  -6, -10],
        [  2,   5,   2,   9,  -1],
        [ -9,  -7,  -4,   1,   9],
        [ -1, -10,   9,   2,   5]])

In [65]:
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [66]:
torch.min(d)

tensor(1.9000)

In [67]:
torch.max(d)

tensor(4.4000)

In [68]:
torch.mean(d)

tensor(3.0750)

In [69]:
torch.argmax(d)

tensor(3)

In [70]:
torch.argmin(d)

tensor(0)

In [72]:
e

tensor([[  1,   5,  -7,  -6, -10],
        [  2,   5,   2,   9,  -1],
        [ -9,  -7,  -4,   1,   9],
        [ -1, -10,   9,   2,   5]])

In [71]:
torch.argmin(e)

tensor(4)

In [73]:
torch.argmax(e)

tensor(8)

In [74]:
torch.sum(e)

tensor(-5)

2*3, 3*2 = 2*2

In [75]:
e

tensor([[  1,   5,  -7,  -6, -10],
        [  2,   5,   2,   9,  -1],
        [ -9,  -7,  -4,   1,   9],
        [ -1, -10,   9,   2,   5]])

In [88]:
e.shape

torch.Size([4, 5])

In [84]:
f = torch.eye(5,4)

In [85]:
f

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [89]:
f.shape

torch.Size([5, 4])

In [90]:
torch.matmul(e,f)

RuntimeError: expected m1 and m2 to have the same dtype, but got: long int != float

In [91]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [92]:
vector2

tensor([3, 4])

In [93]:
torch.dot(vector1, vector2)

tensor(11)

In [103]:
g = torch.randint(size=(2,3), low=0,high=10)

In [104]:
g

tensor([[8, 6, 1],
        [0, 3, 6]])

In [105]:
torch.transpose(g, 0, 1)

tensor([[8, 0],
        [6, 3],
        [1, 6]])

In [106]:
torch.exp(g)

tensor([[2.9810e+03, 4.0343e+02, 2.7183e+00],
        [1.0000e+00, 2.0086e+01, 4.0343e+02]])

In [112]:
# torch.inv(g,0)
g = torch.tensor([[4.0, 7.0], [2.0, 6.0]])

# Compute the inverse
g_inv = torch.linalg.inv(g)  # Use torch.linalg.inv instead of torch.inv for newer versions of PyTorch
print(g_inv)

tensor([[ 0.6000, -0.7000],
        [-0.2000,  0.4000]])


In [113]:
import torch

# Example tensor
g = torch.tensor([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0]])

# Compute softmax along a specific dimension
softmax_g = torch.softmax(g, dim=1)  # dim=1 applies softmax across rows
print(softmax_g)


tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])
